# Generated by Django 2.2.11 on 2020-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.Technologie')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='technologies',
            field=models.ManyToManyField(related_name='persons', through='persons.PersonTech', to='technologies.Technologie'),
        ),
    ]
